const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_12_15_10_31_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTUyLFxuICAgICAgICA3NSxcbiAgICAgICAgNDAsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjE2LFxuICAgICAgICA5MixcbiAgICAgICAgMTEwLFxuICAgICAgICAxNjEsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTkzLFxuICAgICAgICA2NyxcbiAgICAgICAgODcsXG4gICAgICAgIDMzLFxuICAgICAgICAxNzEsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTE5LFxuICAgICAgICA2LFxuICAgICAgICAxMjUsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMjA4LFxuICAgICAgICAyMDUsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMyxcbiAgICAgICAgMTg0LFxuICAgICAgICAyNTUsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjUzLFxuICAgICAgICA5MixcbiAgICAgICAgMjMxLFxuICAgICAgICAyMzksXG4gICAgICAgIDk3LFxuICAgICAgICA2OFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDcsXG4gICAgICAgIDk0LFxuICAgICAgICAxNTksXG4gICAgICAgIDExMSxcbiAgICAgICAgODQsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTk5LFxuICAgICAgICAyNyxcbiAgICAgICAgMzgsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjA5LFxuICAgICAgICAxMTMsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMTEwLFxuICAgICAgICAxOTIsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMjUzLFxuICAgICAgICAyMTAsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTE3LFxuICAgICAgICAxNDcsXG4gICAgICAgIDEsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTg0LFxuICAgICAgICAyOCxcbiAgICAgICAgMjE3LFxuICAgICAgICAyNDgsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMjAwLFxuICAgICAgICAxNDcsXG4gICAgICAgIDE0NyxcbiAgICAgICAgNzZcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDk2LFxuICAgICAgICA2OCxcbiAgICAgICAgMjAwLFxuICAgICAgICAxODcsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMzYsXG4gICAgICAgIDQ2LFxuICAgICAgICAyMDQsXG4gICAgICAgIDM1LFxuICAgICAgICAyNDAsXG4gICAgICAgIDQ5LFxuICAgICAgICAxOTQsXG4gICAgICAgIDEyMixcbiAgICAgICAgMTIxLFxuICAgICAgICAyMzksXG4gICAgICAgIDI1LFxuICAgICAgICA0NSxcbiAgICAgICAgMjA2LFxuICAgICAgICAxMjEsXG4gICAgICAgIDYzLFxuICAgICAgICAxMDMsXG4gICAgICAgIDE0NixcbiAgICAgICAgNjYsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTQsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTU3LFxuICAgICAgICAyMjksXG4gICAgICAgIDIxOCxcbiAgICAgICAgMjAxLFxuICAgICAgICA2NixcbiAgICAgICAgNzRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTg4LFxuICAgICAgICAxNTIsXG4gICAgICAgIDExLFxuICAgICAgICA4OSxcbiAgICAgICAgMTUxLFxuICAgICAgICA4MSxcbiAgICAgICAgMTkzLFxuICAgICAgICAxOTUsXG4gICAgICAgIDE5OSxcbiAgICAgICAgOSxcbiAgICAgICAgMjM1LFxuICAgICAgICAxNzgsXG4gICAgICAgIDQ3LFxuICAgICAgICAxNzQsXG4gICAgICAgIDIwMixcbiAgICAgICAgMjM3LFxuICAgICAgICA0MixcbiAgICAgICAgMjEyLFxuICAgICAgICA1MixcbiAgICAgICAgMTEyLFxuICAgICAgICAxNCxcbiAgICAgICAgMTYyLFxuICAgICAgICAyMjEsXG4gICAgICAgIDM2LFxuICAgICAgICAxNSxcbiAgICAgICAgNzUsXG4gICAgICAgIDExOSxcbiAgICAgICAgNyxcbiAgICAgICAgMzIsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTU4LFxuICAgICAgICA1NVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTI4LFxuICAgICAgICA3MixcbiAgICAgICAgMzcsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTg5LFxuICAgICAgICA0NyxcbiAgICAgICAgNDYsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMjIsXG4gICAgICAgIDc4LFxuICAgICAgICAyMzQsXG4gICAgICAgIDI0LFxuICAgICAgICAxMTMsXG4gICAgICAgIDkzLFxuICAgICAgICAxMzYsXG4gICAgICAgIDQ4LFxuICAgICAgICAxODIsXG4gICAgICAgIDEyLFxuICAgICAgICAyNSxcbiAgICAgICAgMjQ1LFxuICAgICAgICAyNTEsXG4gICAgICAgIDU4LFxuICAgICAgICAxNDQsXG4gICAgICAgIDEyMixcbiAgICAgICAgNzMsXG4gICAgICAgIDIxNSxcbiAgICAgICAgNzksXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxMzcsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTI2XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDk2LFxuICAgICAgICAxMjUsXG4gICAgICAgIDIzOSxcbiAgICAgICAgNzcsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTI2LFxuICAgICAgICAxNTYsXG4gICAgICAgIDE0NixcbiAgICAgICAgNCxcbiAgICAgICAgNjQsXG4gICAgICAgIDQ5LFxuICAgICAgICAyMTAsXG4gICAgICAgIDI0LFxuICAgICAgICA1MyxcbiAgICAgICAgMTIxLFxuICAgICAgICAyMCxcbiAgICAgICAgMCxcbiAgICAgICAgMjYsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjU1LFxuICAgICAgICAyNTUsXG4gICAgICAgIDkyLFxuICAgICAgICA3MSxcbiAgICAgICAgMTAyLFxuICAgICAgICAxNDAsXG4gICAgICAgIDE5LFxuICAgICAgICAxMzQsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjMwLFxuICAgICAgICAyMzAsXG4gICAgICAgIDk5LFxuICAgICAgICAzNFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICA4NixcbiAgICAgICAgICA1NCxcbiAgICAgICAgICAzNixcbiAgICAgICAgICA1MyxcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgMTgsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAxMzgsXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDkzXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDQzLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAxMixcbiAgICAgICAgICAxNjksXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAxMjAsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDI0MyxcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICA5OSxcbiAgICAgICAgICAzOSxcbiAgICAgICAgICAxMTMsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDU4XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDAsXG4gICAgICAgIDY5LFxuICAgICAgICAyMzMsXG4gICAgICAgIDcxLFxuICAgICAgICA3MCxcbiAgICAgICAgODEsXG4gICAgICAgIDksXG4gICAgICAgIDIwOSxcbiAgICAgICAgNDEsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTczLFxuICAgICAgICAzNyxcbiAgICAgICAgMTIzLFxuICAgICAgICAyMDYsXG4gICAgICAgIDcwLFxuICAgICAgICAxNTQsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjI2LFxuICAgICAgICAxNDQsXG4gICAgICAgIDY4LFxuICAgICAgICA3NyxcbiAgICAgICAgMzYsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTM1LFxuICAgICAgICAxMTAsXG4gICAgICAgIDExLFxuICAgICAgICAyMjksXG4gICAgICAgIDE1LFxuICAgICAgICAyMTUsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMjksXG4gICAgICAgIDk1LFxuICAgICAgICAyMzYsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTA5LFxuICAgICAgICAyNixcbiAgICAgICAgMTU5LFxuICAgICAgICAyMjIsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTIxLFxuICAgICAgICA0MyxcbiAgICAgICAgMjYsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTksXG4gICAgICAgIDI1MCxcbiAgICAgICAgMjAzLFxuICAgICAgICA4MCxcbiAgICAgICAgMjE3LFxuICAgICAgICAyMTgsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTM2LFxuICAgICAgICAyMDEsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMTYyLFxuICAgICAgICAxMDQsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTI5LFxuICAgICAgICA3OSxcbiAgICAgICAgNjUsXG4gICAgICAgIDIzLFxuICAgICAgICAyMTksXG4gICAgICAgIDQwLFxuICAgICAgICA3NSxcbiAgICAgICAgOVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTUyLFxuICBcImFkdlNlY3JldEtleVwiOiBcImNPd1VYc1gzZFJBQmprRGlrc1NvME90NUNtbDNRNnJ1SlVuVGZ4ek9XTkk9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTQ3NzMwODQxOTBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkU3N0Y1NTVEMDdCRkMwQkM1NUMwNzQ0MTFGRUJDRUQzXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTczMDM3NjkyNlxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjk0NzczMDg0MTkwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI4OTREQzIzQTJBMkFCQjA5QTk1NjdEQzVGRTBGOUI0RFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MzAzNzY5MjhcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwidXBYcDlCN1RUanlDYjR4OTZ2UWFjUVwiLFxuICBcInBob25lSWRcIjogXCJhNzViOTQ3Zi04NDBhLTRkY2ItODc1OS1mZDc5OTZjMzUyYmZcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNTYsXG4gICAgICA2MixcbiAgICAgIDE4NyxcbiAgICAgIDY2LFxuICAgICAgMjIxLFxuICAgICAgMjQwLFxuICAgICAgMjE4LFxuICAgICAgMjQ0LFxuICAgICAgMTcsXG4gICAgICA3OSxcbiAgICAgIDE1OCxcbiAgICAgIDE2NyxcbiAgICAgIDQ5LFxuICAgICAgMTczLFxuICAgICAgOTcsXG4gICAgICAxNDksXG4gICAgICA2MixcbiAgICAgIDE1NyxcbiAgICAgIDEwMSxcbiAgICAgIDIxM1xuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMjIsXG4gICAgICA3NyxcbiAgICAgIDMxLFxuICAgICAgMTMzLFxuICAgICAgMTc3LFxuICAgICAgMjM2LFxuICAgICAgNTcsXG4gICAgICAxMDIsXG4gICAgICA3NSxcbiAgICAgIDg5LFxuICAgICAgNjUsXG4gICAgICAxNTgsXG4gICAgICAxNTMsXG4gICAgICAxMjksXG4gICAgICAxMDMsXG4gICAgICA5NixcbiAgICAgIDE2MSxcbiAgICAgIDE2NSxcbiAgICAgIDQwLFxuICAgICAgMjEwXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIkVNTjYzWjlQXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5NDc3MzA4NDE5MDo5QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIyNTA4OTkxNzE2NTU3MDQ6OUBsaWRcIixcbiAgICBcIm5hbWVcIjogXCIsKi0tOiAgTkVUSFVTSEEgIDotLSosXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSjdPcTlJRkVOYnBqYmtHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJHY3g5YUJZL1BRcnRiWWVVT0RjVVNmMG9sSGNoS3pjdi9vZG9SanBLdGlRPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcImwyRDBoZS9FUE42NnpYWWhnOFdiNHovQmZmaTd5ZDZHVGFuS2ZpdVNsS2FocWVQelFleFVxcjZHVmx5TFU4QkhLekVLaXIxeHZXL3BPbk45RExrM0RnPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIjY3SDU5VS9OcFVLdmJGM0FQQWttdUFqdWdQYm9rSDdsSU52RXNHYkFrWGFscGRFTUJ0VWs5NXFPRHBZbGtteG9ZYlJPYmU1UmlnWVBmSEQvU3FUT0NRPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjk0NzczMDg0MTkwOjlAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAyMixcbiAgICAgICAgICA2MyxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDEzNSxcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDE0OCxcbiAgICAgICAgICAxMTksXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgNDcsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDEzNSxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgNzAsXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDM2XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MzAzNzY5MjIsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFHV2ZcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUdXZi5qc29uIjogIntcImtleURhdGFcIjpcIkRnTXM4ZWdWSVNrd2FSUnpScXRZK1Q4bXBDbU8zOVhPTjRSenQ0YkFKdHc9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTUxNDg1ODI3MCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzMwMzc2OTIzOTk4XCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
